table fact_monthly_snapshot
	lineageTag: b25c9dd4-08e9-40b4-8975-a792b95a3b54

	column EmployeeID
		dataType: string
		lineageTag: 26ca4f16-9257-4f68-b4c1-6680e4872c69
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column DepartmentID
		dataType: string
		lineageTag: 7f62c7db-ded0-452f-83e5-e35b64446b8a
		summarizeBy: none
		sourceColumn: DepartmentID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 379739a3-010b-4116-81a6-1627a9894155
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column JobLevelID
		dataType: string
		lineageTag: 07bae862-9146-4dd8-a91c-d7b289d05a3c
		summarizeBy: none
		sourceColumn: JobLevelID

		annotation SummarizationSetBy = Automatic

	column MonthEnd
		dataType: dateTime
		formatString: Long Date
		lineageTag: 66565a6c-6b2d-437e-8028-0a98054291d9
		summarizeBy: none
		sourceColumn: MonthEnd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HireDate = ```
			RELATED(dim_employee[HireDate]) 
			```
		formatString: General Date
		lineageTag: 2baf2246-c655-4fd2-b046-5856a74764d8
		summarizeBy: none

		variation Variation
			isDefault
			relationship: a8e27c27-c260-45d9-bdc5-ceaa49ef0225
			defaultHierarchy: LocalDateTable_e78b73b1-2a15-4702-b9d7-5a91321eeb14.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Tenure Years' =
			
			DIVIDE(
			    DATEDIFF(
			        fact_monthly_snapshot[HireDate],
			        fact_monthly_snapshot[MonthEnd],
			        DAY
			    ),
			    365.25  -- taking fractional years into consideration
			)
		formatString: 0.00
		lineageTag: 5d1ec06b-dc1a-4bd8-88b4-7db876ef9db4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tenure Bucket' =
			
			VAR TenureYrs = [Tenure Years]
			RETURN
			SWITCH(
			    TRUE(),
			    TenureYrs < 1, "<1 year",
			    TenureYrs < 3, "1–3 years",
			    TenureYrs < 5, "3–5 years",
			    "5+ years"
			)
		lineageTag: 2ad3ee56-a151-4112-9a0e-719016dcbddf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_monthly_snapshot = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\monthly_snapshot.csv"),[Delimiter=",", Encoding=65001]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", type text}, {"DepartmentID", type text}, {"Gender", type text}, {"JobLevelID", type text}, {"MonthEnd", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

